# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js base image
FROM node:18-slim

# Install the project into `/app`
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies (use npm install since no package-lock.json)
RUN npm install --production

# Copy server code
COPY server.js ./

# Expose the port (Smithery will inject PORT env var)
EXPOSE 8000

# Run the Node.js server
CMD ["node", "server.js"]

