# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js base image
FROM node:18-slim

# Install the project into `/app`
WORKDIR /app

# Copy package files first for better caching
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the application
COPY server.js ./

# Expose the port (Smithery will inject PORT env var)
EXPOSE 8000

# Run the Node.js server
CMD ["node", "server.js"]

